### ISSUE TITLE
Drush aliases can't find document root

### ISSUE THREAD

**Issue by chase-conklin** [platformsh/platformsh-cli#772] opened 2019-01-25 22:25 UTC
With the latest release, v3.39.0, our team's drush aliases can't find the document root after regenerating. We have to manually add the `/app` directory before our document root to our alias files for the aliases to function properly. Our sites are currently running Drupal 8.6.7 and Drush 9.4.

**Comment by penance316** [comment] 2019-01-29 09:46
I can confirm I have been the same issue for the last few weeks.
Drush 9.4.

My current workaround is to delete the line
`root: web` 
from my yml aliases.

**Comment by hanoii** [comment] 2019-01-30 19:21
Yup, same for me

**Comment by justgable** [comment] 2019-01-30 21:16
Reverting back to 3.38.1 version of the CLI has temporarily resolved this issue while I wait for an official fix.

https://github.com/platformsh/platformsh-cli/releases/tag/v3.38.1

**Comment by pjcdawkins** [comment] 2019-02-01 17:33
It seems the problem is if you run Drush inside a site that requires a different major version from your globally installed Drush.

For example, if you have Drush 9 installed as the user, but you run Drush inside a Drupal site that requires Drush 8.

With Drush 8 everywhere or Drush 9 everywhere, there is no problem.

**Comment by hanoii** [comment] 2019-02-05 12:20
I have drush 8 globally and drush 9 local  on most projects, but there's no error to be honest, it works, it's only that the root on the alias is wrong. Do we need to have it if removing it fixes it?

**Comment by baltazarz3** [comment] 2019-02-08 16:49
I run into the same problem as hanoii, global drush v8 and one local project on v9. Removing the root worked, I hope this gets fixed on the next release.

**Comment by hanoii** [comment] 2019-02-08 18:56
Removing it affects rsync, so it has to be /app/web as before or the proper path rather than just web

**Comment by baltazarz3** [comment] 2019-02-08 19:04
Confirmed: removing the root breaks the rsync and /app/web worked.

**Comment by pjcdawkins** [comment] 2019-02-15 10:25
I'm trying to track down the 'root' cause here. I don't see where in the source code of Drush 8 or 9 that an absolute path is required for the 'root', a relative one should work as it seems both do `realpath()` first then a `chdir()` later... and a relative path does work for me except when I have a global 9 and local 8 or vice versa. Trying to understand the conflict between them... 😞

**Comment by pjcdawkins** [comment] 2019-02-15 11:06
... it turns out the important version number is the one installed on the remote.

Drush 9 (on the remote) doesn't handle the relative path. There is an alternative - it would replace `~/` with the home directory. Sadly, Drush 8 is the opposite: it does handle the relative path, yet it does not do the tilde expansion.

The CLI can't find the drush version on the remote, but it can guess, based on the drush version installed in the site locally.

**Comment by pjcdawkins** [comment] 2019-02-15 15:35
Somehow in Drush 9 this method fails on `web` but not on the absolute `/app/web` or even the relative `../app/web`:

https://github.com/webflo/drupal-finder/blob/1.1.0/src/DrupalFinder.php#L86

**Comment by pjcdawkins** [comment] 2019-02-15 16:28
This is mostly resolved by #777 (merged) - but there would be issues with a locally installed 8 and remotely installed 9, until Drush 9 has been fixed to accept relative paths in all instances (see the DrupalFinder PR 40 referenced above).

**Comment by hanoii** [comment] 2019-02-18 16:42
@pjcdawkins just updated to 3.40.2 and recreated on alias on a project. I have drush 8 globally but drush 9.5.2 on both remote and project local.

`drush version` locally gives 9.5.2.

A regular drush sql-sync gives me the following:

```
In Path.php line 587:
                                                  
  [InvalidArgumentException]                      
  The base path "~/web" is not an absolute path.  
                                                  

Exception trace:
 () at /Users/ariel/Sites/hanoii/charlas/vendor/webmozart/path-util/src/Path.php:587
 Webmozart\PathUtil\Path::makeAbsolute() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/site-alias/src/HostPath.php:148
 Consolidation\SiteAlias\HostPath->getPath() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/site-alias/src/HostPath.php:231
 Consolidation\SiteAlias\HostPath->fullyQualifiedPath() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/site-alias/src/HostPath.php:247
 Consolidation\SiteAlias\HostPath->fullyQualifiedPathPreservingTrailingSlash() at /Users/ariel/Sites/hanoii/charlas/vendor/drush/drush/src/Commands/core/RsyncCommands.php:63
 Drush\Commands\core\RsyncCommands->rsync() at n/a:n/a
 call_user_func_array() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /Users/ariel/Sites/hanoii/charlas/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /Users/ariel/Sites/hanoii/charlas/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/ariel/Sites/hanoii/charlas/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/ariel/Sites/hanoii/charlas/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /Users/ariel/Sites/hanoii/charlas/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/ariel/Sites/hanoii/charlas/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /Users/ariel/Sites/hanoii/charlas/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /Users/ariel/Sites/hanoii/charlas/vendor/drush/drush/drush.php:66
 require() at /Users/ariel/Sites/hanoii/charlas/vendor/drush/drush/drush:4
```

Seems to fail on the rsync of the dump.

Is this the issue you mentioned? Why is that, shouldn't version 9 be used on both on this case?

**Comment by pjcdawkins** [comment] 2019-02-18 17:33
The `~/` version is what works for version 9 (try `drush @alias status`)... but apparently not for rsync?? Maybe the path is handled differently in different places...

**Comment by hanoii** [comment] 2019-02-18 17:38
@pjcdawkins yes, `status` work, `sql-sync` doesn't and I think underneath it uses `core:rsync`

Why not going back to absolute, it was like that before 3.39?

**Comment by pjcdawkins** [comment] 2019-03-22 17:22
This should be resolved since v3.40.3, with the exception of Integrated Enterprise projects, which will require running `platform drush-aliases` to update aliases with the correct web root directory.

**Closed by pjcdawkins** 2019-03-22 17:22 UTC

**Comment by pjcdawkins** [comment] 2019-11-02 21:02
The above proposes to remove the CLI workaround, because newer Drush 9 versions (since 9.6.2) appear to support relative paths in alias definitions.

**Comment by pjcdawkins** [comment] 2020-11-16 16:34
Just noting that #869 was merged, but reverted a month later in Dec 2019. The Drush behavior is inconsistent between commands, e.g. it doesn't work for `sql-sync`.
