### ISSUE TITLE
Check for new CLI versions on command run

### ISSUE THREAD

**Issue by budda** [platformsh/platformsh-cli#339] opened 2015-09-08 10:30 UTC
A lot of popular CLI tools these days report if a newer version of the tool is available when a command is executed.

It would be nice to implement a reminder to upgrade the Platform CLI tool if the current version is old.

**Comment by pjcdawkins** [comment] 2015-09-08 10:32
Agreed - this should be possible after a move to a new install method (see https://github.com/platformsh/platformsh-cli/pull/338)

**Comment by pjcdawkins** [comment] 2015-09-09 20:25
A vague plan:

1. Write a timestamp in the phar to show when it was built (Composer does this)
2. Also, write a timestamp to a file to show when we have last checked for updates, e.g. in something like `~/.platformsh/cli.conf.yaml`
3. If (phar age > 7 days) and (not already checked in the last day), check for a new version, and offer to update
4. Allow switching off automatic updates altogether via config (again, `~/.platformsh/cli.conf.yaml`), and perhaps via a command

**Comment by ralt** [comment] 2015-09-09 20:27
For 1., please make it based on a timestamp stored in a file, such as the changelog. Writing a timestamp based on the build time prevents any kind of reproducible build.

**Comment by pjcdawkins** [comment] 2015-09-09 20:30
Agreed... this could even allow the version's date to be reported in `platform --version`.

And yes I should probably be committing a changelog too.

**Comment by ralt** [comment] 2015-09-09 20:31
1. and 2. seem redundant, don't they? Just write a timestamp if no timestamp exists (so, it will be the 1st time `platform` is run)

Or maybe not, since it would let you know if you installed then started running `platform` a month later. But it would let you have less code... not sure.

**Comment by pjcdawkins** [comment] 2015-09-09 20:33
I was thinking the two-pronged approach would avoid the annoyance (e.g. from Composer) of warning the user frequently, and avoid the performance impact of checking for updates frequently.

**Comment by ralt** [comment] 2015-09-09 20:35
I didn't mean to remove 2 completely, just to remove 1. So you wouldn't
have the annoyance, since the check would still happen once a day. Just
that the first timestamp wouldn't be the last changelog entry's, but the
first time `platform` was run.

On Wed, Sep 9, 2015 at 10:33 PM, Patrick Dawkins <notifications@github.com>
wrote:

> I was thinking the two-pronged approach would avoid the annoyance (e.g.
> from Composer) of warning the user frequently, and avoid the performance
> impact of checking for updates frequently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/platformsh/platformsh-cli/issues/339#issuecomment-139037756>
> .
>



-- 
Florian Margaine

**Comment by pjcdawkins** [comment] 2016-02-29 16:48
Added in v2.8.1

**Closed by pjcdawkins** 2016-02-29 16:48 UTC
Labels: new feature
