### ISSUE TITLE
'platform build' fails locally for profiles with Drush <= 6.4

### ISSUE THREAD

**Issue by nvahalik** [platformsh/platformsh-cli#402] opened 2015-12-21 18:09 UTC
Working on an install profile and getting an error message when trying to build the profile locally. This doesn't happen when I push to the project remotely. It builds when pushing to Platform.sh.

> ~/Platform.sh/mmcp/repository$ platform build
> Building application php (runtime type: php:5.6)
>   Beginning to build                                                   [ok]
>   /Users/nvahalik/Platform.sh/mmcp/repository/project-core.make.
>   drupal-7.41 downloaded.                                              [ok]
>   drupal patched with                                                  [ok]
>   install-redirect-on-empty-database-728702-36.patch.
>   Generated PATCHES.txt file for drupal                                [ok]
> Building the profile: mmcp
>   Base path                                                            [error]
>   /Users/nvahalik/Platform.sh/mmcp/builds/2015-12-21--12-00-13--master/public/profiles/mmcp
>   already exists.
> 
> 
>                                                                                                                                                                                             
>   [Exception]                                                                                                                                                                               
>   The command failed with the exit code: 1                                                                                                                                                  
>   Full command: '/Users/nvahalik/.composer/vendor/bin/drush' 'make' '--no-core' '--contrib-destination=.' '/Users/nvahalik/Platform.sh/mmcp/repository/project.make' '/Users/  
>   nvahalik/Platform.sh/mmcp/builds/2015-12-21--12-00-13--master/public/profiles/mmcp' '--yes' '--cache-duration-releasexml=300' '--concurrency=4'                              
>                                                                                                                                                                                             
> 
> 
> local:build [-a|--abslinks] [--source SOURCE] [--destination DESTINATION] [--copy] [--no-clean] [--no-archive] [--no-cache] [--no-build-hooks] [--working-copy] [--concurrency CONCURRENCY] [--lock] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [-y|--yes] [-n|--no] [-s|--shell] [--] <command> [<app>]...

My repository is pretty sparse right now:

> ~/Platform.sh/mmcp/repository$ ls -al
> total 80
> drwxr-xr-x  14 nvahalik  staff    476 Dec 21 11:18 .
> drwxr-xr-x   8 nvahalik  staff    272 Dec 21 09:21 ..
> drwxr-xr-x  16 nvahalik  staff    544 Dec 21 12:06 .git
> drwxr-xr-x   4 nvahalik  staff    136 Dec 21 09:20 .platform
> -rw-r--r--   1 nvahalik  staff   1641 Dec 21 09:20 .platform.app.yaml
> -rw-r--r--   1 nvahalik  staff   1558 Dec 21 09:20 README.md
> drwxr-xr-x   3 nvahalik  staff    102 Dec 21 09:20 libraries
> -rw-r--r--@  1 nvahalik  staff   2152 Dec 21 11:46 mmcp.info
> -rw-r--r--@  1 nvahalik  staff  14304 Dec 21 12:05 mmcp.install
> -rw-r--r--@  1 nvahalik  staff    955 Dec 21 11:10 mmcp.profile
> drwxr-xr-x   3 nvahalik  staff    102 Dec 21 09:20 modules
> -rw-r--r--@  1 nvahalik  staff    196 Dec 21 11:39 project-core.make
> -rw-r--r--@  1 nvahalik  staff   3975 Dec 21 11:58 project.make
> drwxr-xr-x   3 nvahalik  staff    102 Dec 21 09:20 themes

**Comment by ralt** [comment] 2015-12-21 18:19
What's your CLI version?

**Comment by nvahalik** [comment] 2015-12-21 18:24
@ralt, I was using v2.8.3 but I tried again with v2.10.0 and encountered the same issue.

**Comment by pjcdawkins** [comment] 2015-12-22 09:33
Could you try with v2.7.1 ([here's the platform.phar file](https://github.com/platformsh/platformsh-cli/releases/download/v2.7.1/platform.phar))? I suspect this commit could be the reason: https://github.com/platformsh/platformsh-cli/commit/d6bb673088526a774aa6ab26b728153dc6172ee5

**Comment by pjcdawkins** [comment] 2015-12-22 09:34
Also, what is your Drush version?

**Comment by nvahalik** [comment] 2015-12-22 17:49
I am using Drush v6.2.0. Using the provided .phar file (v2.7.1) I did not have any errors when building the site.

**Comment by pjcdawkins** [comment] 2015-12-23 00:07
OK, I've reproduced this with Drush <= 6.4, but it's fixed from 6.5 onwards (by [this PR](https://github.com/drush-ops/drush/pull/919/files)).

I can work on a backwards compatibility fix for the CLI.

**Comment by pjcdawkins** [comment] 2015-12-29 17:26
Fixed in v2.10.1

**Closed by pjcdawkins** 2015-12-29 17:26 UTC
